const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CHANGE_QTY = 'CHANGE_QTY';
const TOGGLE_SAVED = 'TOGGLE_SAVED';

export { ADD_TO_CART, REMOVE_FROM_CART, CHANGE_QTY, TOGGLE_SAVED };
